name: Echo system type

on:
  workflow_dispatch:

jobs:
  echo:
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Echo the system type
        shell: bash
        run: |
          if [[ "$OSTYPE" == "linux-gnu"* ]]; then
            echo "Linux"
          elif [[ "$OSTYPE" == "darwin"* ]]; then
            echo "macOS"
          elif [[ "$OSTYPE" == "cygwin" ]]; then
            echo "Cygwin"
          elif [[ "$OSTYPE" == "msys" ]]; then
            echo "Windows MSYS"
          elif [[ "$OSTYPE" == "win32" ]]; then
            echo "Windows"
          elif [[ "$OSTYPE" == "freebsd"* ]]; then
            echo "FreeBSD"
          else
            echo "Unknown"
          fi
